### ISSUE TITLE
XfconfError: the type 'uint64' of 'thunar/misc-thumbnail-max-file-size' is not supported.

### ISSUE THREAD

**Issue by superjamie** [jamescherti/watch-xfce-xfconf#1]
Thank you for this cool looking tool! Unfortunately I wasn't able to get it running on Debian 12 with XFCE 4.18. To my knowledge I'm not doing anything tricky with XFCE. I expect you could reproduce this using the [current Debian 12 XFCE LiveCD](https://cdimage.debian.org/debian-cd/current-live/amd64/iso-hybrid/debian-live-12.2.0-amd64-xfce.iso).

```
$ pipx install watch-xfce-xfconf
  installed package watch-xfce-xfconf 1.0.4, installed using Python 3.11.2
  These apps are now globally available
    - watch-xfce-xfconf
done! ✨ 🌟 ✨
$ watch-xfce-xfconf 
[INFO] You can start modifying 'XFCE 4' settings with 'xfce4-settings-manager'. Your changes will be displayed in this terminal...

Traceback (most recent call last):
  File "/home/username/.local/bin/watch-xfce-xfconf", line 8, in <module>
    sys.exit(watch_xfce_xfconf())
             ^^^^^^^^^^^^^^^^^^^
  File "/home/username/.local/pipx/venvs/watch-xfce-xfconf/lib/python3.11/site-packages/watch_xfce_xfconf/__init__.py", line 64, in watch_xfce_xfconf
    xfconf_query_list = Xfconf()
                        ^^^^^^^^
  File "/home/username/.local/pipx/venvs/watch-xfce-xfconf/lib/python3.11/site-packages/watch_xfce_xfconf/xfconf.py", line 103, in __init__
    self._parse_xfconf_perchannel_xml(str(xml_file))
  File "/home/username/.local/pipx/venvs/watch-xfce-xfconf/lib/python3.11/site-packages/watch_xfce_xfconf/xfconf.py", line 179, in _parse_xfconf_perchannel_xml
    raise XfconfError(err_str)
watch_xfce_xfconf.xfconf.XfconfError: the type 'uint64' of 'thunar/misc-thumbnail-max-file-size' is not supported. XML file: '/home/username/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml'
```

The contents of that XML file are:

```
/home/username/.config/xfce4/xfconf/xfce-perchannel-xml/thunar.xml

<?xml version="1.0" encoding="UTF-8"?>

<channel name="thunar" version="1.0">
  <property name="last-view" type="string" value="ThunarDetailsView"/>
  <property name="misc-single-click" type="bool" value="false"/>
  <property name="default-view" type="string" value="ThunarDetailsView"/>
  <property name="misc-thumbnail-mode" type="string" value="THUNAR_THUMBNAIL_MODE_NEVER"/>
  <property name="misc-thumbnail-max-file-size" type="uint64" value="524288"/>
  <property name="last-details-view-zoom-level" type="string" value="THUNAR_ZOOM_LEVEL_38_PERCENT"/>
  <property name="last-details-view-column-widths" type="string" value="50,50,136,50,50,50,50,50,128,50,50,72,50,343"/>
</channel>
```

In **File Manager Settings** I have set **Only show thumbnails for files smaller than: 512 KiB** which looks to be the problem value.

Please let me know if there's anything more I can provide or test.

**Comment by jamescherti** [comment]
Thank you for bringing this issue to my attention, @superjamie .  I appreciate your feedback. 

I have just committed a quick fix. Kindly proceed to install the latest version using the following command:
```
pip install --user git+https://github.com/jamescherti/watch-xfce-xfconf.git
```

Then, you can execute watch-xfce-xfconf using:
``` 
~/.local/bin/watch-xfce-xfconf
```

Could you please confirm that the issue has been fixed?

**Comment by superjamie** [comment]
Yes, confirmed all working now.

Thank you for the quick reply and fix!

**Comment by jamescherti** [comment]
You're welcome, @superjamie . I am glad to head that the issue has been resolved. If you have any further question or suggestion, feel free to reach out!
